# Generated by Django 3.2.15 on 2022-09-11 10:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jee_mains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=1000, null=True)),
                ('year', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('shift', models.CharField(default='', max_length=100, null=True)),
                ('question', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=5000), size=None)),
                ('question_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=5000), size=None)),
                ('solution_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=5000), size=None)),
                ('correct_option', models.CharField(default='', max_length=100, null=True)),
                ('solution', models.TextField()),
                ('times_loaded', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
