# Generated by Django 3.2.15 on 2022-09-11 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220911_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='jee_mains',
            name='option_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=5000), default=[], size=None),
            preserve_default=False,
        ),
    ]
