# Generated by Django 3.2.15 on 2022-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_jee_mains_option_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='jee_mains',
            name='subject',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
