# Generated by Django 3.2.15 on 2022-09-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220913_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jee_mains',
        ),
    ]
