# Generated by Django 3.2.15 on 2022-09-16 06:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jee_mains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=1000, null=True)),
                ('year', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('shift', models.CharField(default='', max_length=100, null=True)),
                ('question', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=5000), size=None)),
                ('subject', models.CharField(default='', max_length=100, null=True)),
                ('question_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=5000, null=True), size=None)),
                ('solution_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=5000, null=True), size=None)),
                ('option_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=[], max_length=5000, null=True), size=None)),
                ('correct_option', models.CharField(default='', max_length=100, null=True)),
                ('solution', models.TextField()),
                ('times_loaded', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
    ]
