# Generated by Django 3.2.15 on 2022-10-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jee_mains', '0002_alter_jee_mains_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jee_mains',
            name='month',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
