# Generated by Django 3.2.15 on 2022-10-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jee_mains', '0003_alter_jee_mains_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jee_mains',
            name='date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jee_mains',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
