# Generated by Django 3.2.15 on 2022-10-15 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jee_mains', '0004_auto_20221015_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSeriesMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics_ques_map', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[]), size=None)),
                ('chemistry_ques_map', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[]), size=None)),
                ('maths_ques_map', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[]), size=None)),
            ],
        ),
    ]
