# Generated by Django 3.2.15 on 2022-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jee_mains', '0006_auto_20221021_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jee_mains',
            name='option1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jee_mains',
            name='option2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jee_mains',
            name='option3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jee_mains',
            name='option4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='jee_mains',
            name='subject',
            field=models.TextField(default='', null=True),
        ),
    ]
